name: Build and Update Release

on:
  push:
    branches:
      - main

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Build
      run: wasm-pack build --target web

    - name: Compress pkg directory
      run: tar -czvf gsea-rs.tar.gz pkg

    - name: Update Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        name: Latest Release
        files: |
          gsea-rs.tar.gz
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
